export const LOADING_TIPS: string[] = [
    "Fun fact: The first email was sent in 1971!",
    "Tip: Ctrl + Shift + T reopens your last closed browser tab.",
    "Did you know? Angular was originally called 'AngularJS'.",
    "Pro tip: Write commit messages like you're leaving notes for your future self.",
    "Fun fact: The first computer virus was created in 1983.",
    "Tip: Use 'git stash' to save your changes temporarily.",
    "Did you know? The first website is still online! Check it out at info.cern.ch.",
    "Fun fact: The first computer mouse was made of wood.",
    "There are more pyramids in Sudan than in Egypt.",
    "In 1999, PayPal was voted one of the worst business ideas of the year.",
    "Your tongue print is as unique as your fingerprint.",
    "Bananas are radioactive — they contain potassium-40.",
    "The Amazon River once flowed in the opposite direction.",
    "The first domain name ever registered was symbolics.com in 1985.",
    "Water can boil and freeze at the same time in a process called the triple point.",
    "Mount Everest grows about 4 millimeters every year.",
    "TYPEWRITER is the longest word you can type using only the top row of a QWERTY keyboard.",
    "The Eiffel Tower grows in summer due to thermal expansion.",
    "Scotland's national animal is the unicorn.",
    "Some cats are allergic to humans.",
    "Africa is the only continent in all four hemispheres.",
    "The word 'nerd' was first coined by Dr. Seuss.",
    "Canada has more lakes than the rest of the world combined.",
    "A day on Venus is longer than its year.",
    "The human nose can detect about 1 trillion smells.",
    "Email existed before the world wide web.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "Oxford University is older than the Aztec Empire.",
    "The shortest war in history lasted 38 minutes — between Britain and Zanzibar.",
    "Istanbul is the only city located on two continents.",
    "Vikings used bones to make their combs.",
    "The original iPod could hold 5GB of storage — about 1,000 songs.",
    "Australia is wider than the moon.",
    "The current US flag was designed by a 17-year-old for a school project — and got a B-.",
    "The first webcam watched a coffee pot at Cambridge University.",
    "The Great Fire of London in 1666 destroyed 80% of the city — but only 6 people were recorded dead.",
    "The Leaning Tower of Pisa took over 199 years to build.",
    "Octopuses have three hearts.",
    "There's enough DNA in the human body to stretch from the sun to Pluto and back — 17 times.",
    "A teaspoon of a neutron star would weigh about 6 billion tons.",
    "The first mobile phone weighed over 2 pounds.",
    "Russia spans 11 time zones.",
    "There's a town in Norway called Hell — and it freezes over every winter.",
    "Antarctica is the driest, windiest, and coldest continent.",
    "Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid.",
    "Light from the Sun takes 8 minutes and 20 seconds to reach Earth.",
    "Sharks are older than trees — they've been around for 400 million years.",
    "The first computer virus was created in 1986 and was called 'Brain'.",
    "The inventor of the microwave appliance only received $2 for his discovery.",
    "You can hear a blue whale's heartbeat from over 2 miles away.",
    "CAPTCHA stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart'.",
    "The @ symbol was chosen for email because it was rarely used otherwise.",
];